// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhh4ldiMqvr2HFwemUtcE5fBGaxXM9So8',
    appId: '1:127580395532:web:1223f77f4eea748cc27629',
    messagingSenderId: '127580395532',
    projectId: 'theflaggang-2a26b',
    authDomain: 'theflaggang-2a26b.firebaseapp.com',
    storageBucket: 'theflaggang-2a26b.appspot.com',
    measurementId: 'G-G98BECLVD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEcugQJ4rf5Lfy0U1uCMvZG58wGoeBnYQ',
    appId: '1:127580395532:android:89cb279ce7c3fae1c27629',
    messagingSenderId: '127580395532',
    projectId: 'theflaggang-2a26b',
    storageBucket: 'theflaggang-2a26b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5gVuZra3ArYwWfRjJmV_nJQtrQiHxRcY',
    appId: '1:127580395532:ios:ba050c0a4caed40fc27629',
    messagingSenderId: '127580395532',
    projectId: 'theflaggang-2a26b',
    storageBucket: 'theflaggang-2a26b.appspot.com',
    iosBundleId: 'ca.ipsofactointeractif.theflaggangapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5gVuZra3ArYwWfRjJmV_nJQtrQiHxRcY',
    appId: '1:127580395532:ios:ba050c0a4caed40fc27629',
    messagingSenderId: '127580395532',
    projectId: 'theflaggang-2a26b',
    storageBucket: 'theflaggang-2a26b.appspot.com',
    iosBundleId: 'ca.ipsofactointeractif.theflaggangapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhh4ldiMqvr2HFwemUtcE5fBGaxXM9So8',
    appId: '1:127580395532:web:0e0c0946c4392fcbc27629',
    messagingSenderId: '127580395532',
    projectId: 'theflaggang-2a26b',
    authDomain: 'theflaggang-2a26b.firebaseapp.com',
    storageBucket: 'theflaggang-2a26b.appspot.com',
    measurementId: 'G-VZEY66M2JS',
  );
}
